version: '3'
services:
  kinetic_base:
    build:
      dockerfile: Dockerfile
      context: ./kinetic/
    image: bitbots/bitbots-industrial:kinetic-base
  melodic_base:
    build:
      dockerfile: Dockerfile
      context: ./melodic/
    image: bitbots/bitbots-industrial:melodic-base