version: '3'
services:
  kinetic_base:
    build:
      dockerfile: Dockerfile
      context: .
      args:
        ROS_DISTRO: kinetic
    image: bitbots/bitbots-industrial:kinetic-base
  melodic_base:
    build:
      dockerfile: Dockerfile
      context: .
      args:
        ROS_DISTRO: melodic
    image: bitbots/bitbots-industrial:melodic-base
  noetic_base:
    build:
      dockerfile: Dockerfile
      context: .
      args:
        ROS_DISTRO: noetic
    image: bitbots/bitbots-industrial:noetic-base
