version: "3.0"
services:
    ros_kinetic_container:
        image: bitbots/bitbots-industrial:kinetic-base
        volumes:
            - /tmp/.X11-unix:/tmp/.X11-unix:rw
            - $HOME/.rviz:/home/robocup/.rviz  # include if any specific rviz settings are needed
        environment:
            - DISPLAY=$DISPLAY
            - QT_X11_NO_MITSHM=1
            - ROBOT=youbot-brsu-4   # Can be modified here if necessary
            - ROBOT_ENV=brsu-c025-sim # For youbot simulation
        devices:
            - /dev/dri:/dev/dri
        privileged: true
        tty: true
        network_mode: "host"
    ros_melodic_container:
        image: bitbots/bitbots-industrial:melodic-base
        volumes:
            - /tmp/.X11-unix:/tmp/.X11-unix:rw
            - $HOME/.rviz:/home/robocup/.rviz  # include if any specific rviz settings are needed
        environment:
            - DISPLAY=$DISPLAY
            - QT_X11_NO_MITSHM=1
            - ROBOT=youbot-brsu-4   # Can be modified here if necessary
            - ROBOT_ENV=brsu-c025-sim # For youbot simulation
        devices:
            - /dev/dri:/dev/dri
        privileged: true
        tty: true
        network_mode: "host"
    ros_noetic_container:
        image: bitbots/bitbots-industrial:noetic-base
        volumes:
            - /tmp/.X11-unix:/tmp/.X11-unix:rw
            - $HOME/.rviz:/home/robocup/.rviz
        environment:
            - DISPLAY=$DISPLAY
            - QT_X11_NO_MITSHM=1
            - ROBOT=youbot-brsu-4   # Can be modified here if necessary
            - ROBOT_ENV=brsu-c025-sim # For youbot simulation
        devices:
            - /dev/dri:/dev/dri
        privileged: true
        tty: true
        network_mode: "host"
